### ISSUE TITLE
wrapper hatalı

### ISSUE THREAD

**Issue by yorunoken** [onur2677/iett-api#1]
test.js kodunu çalıştırdığımda bu hatayı veriyor:
```
Error HatDurakGuzergah faultcode: soapenv:Server faultstring: Policy Falsified faultactor: https://api.ibb.gov.tr/iett/UlasimAnaVeri/HatDurakGuzergah.asmx detail: {"policyResult":{"$attributes":{"status":"Error in Assertion Processing"}}}
```

**Comment by onur2677** [comment]
![image](https://github.com/onur2677/iett-api/assets/23284052/c0fd58f1-6636-4773-8c0d-902128a6775d)

ilgili hata soap servisin kendisinden geliyor.

**Comment by onur2677** [comment]
![image](https://github.com/onur2677/iett-api/assets/23284052/1f8d0424-ef25-4ecd-8471-260eae08d08c)
